version: '3.5'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/app
      - ./nginx_conf/docker.conf:/etc/nginx/conf.d/docker.conf
    links:
      - php-fpm
  php-fpm:
    image: php:8-fpm
    build:
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: otus

  adminer:
    image: adminer
    restart: always
    ports:
      - 5432:5432
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    ports:
#      - "3386:3306"
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root