version: '3.5'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/app
      - ./nginx_conf/docker.conf:/etc/nginx/conf.d/docker.conf
    links:
      - php-fpm

  php-fpm:
#    image: php:8-fpm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/app

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: otus

  adminer:
    image: adminer
    restart: always
    ports:
      - 5432:5432